- API: https://api.weatherbit.io/v2.0/history/airquality?city=Hanoi&start_date=2024-02-08&end_date=2024-03-08&tz=local&key=API_KEY

In [13]:
import requests as req
import pandas as pd
from datetime import datetime, timedelta
from calendar import monthrange

In [19]:
def get_weather_data(start_date, end_date, api_key):
    url = f"https://api.weatherbit.io/v2.0/history/airquality"
    params = {
        'city': 'Hanoi',
        'start_date': start_date,
        'end_date': end_date,
        'tz': 'local',
        'key': api_key
    }

    response = requests.get(url, params=params, verify=False)
    if response.status_code == 200:
        data = response.json()
        records = data.get('data', [])
        df = pd.DataFrame(records)
        return df
    else:
        print(f"Error: {response.status_code}")
        return None

In [26]:
def save_data_to_csv(data, file_name):
    if data is not None and 'data' in data and len(data['data']) > 0:
        records = data['data']
        print(f"Saving {len(records)} records.")  # In ra số bản ghi đang được lưu
        df = pd.DataFrame(records)
        df.to_csv(file_name, index=False, mode='a', header=not pd.io.common.file_exists(file_name))
        print(f"Data saved to {file_name}")
    else:
        print("No valid data to save.")

In [16]:
def get_months_between_dates(start_date, end_date):
    months = []
    start_year, start_month = start_date.year, start_date.month
    end_year, end_month = end_date.year, end_date.month

    while start_year < end_year or (start_year == end_year and start_month <= end_month):
        # Tạo start_date và end_date cho từng tháng
        start = datetime(start_year, start_month, 1)
        _, last_day = monthrange(start_year, start_month)  # Lấy số ngày cuối tháng
        end = datetime(start_year, start_month, last_day)

        months.append((start.strftime('%Y-%m-%d'), end.strftime('%Y-%m-%d')))

        # Chuyển sang tháng tiếp theo
        if start_month == 12:
            start_month = 1
            start_year += 1
        else:
            start_month += 1

    return months

In [17]:
API_KEY = 'bd78df23972d4c5787e72fd978e7c5cb'
start_date = datetime(2023, 1, 1)
end_date = datetime.today()  

months = get_months_between_dates(start_date, end_date)
print(months)

[('2023-01-01', '2023-01-31'), ('2023-02-01', '2023-02-28'), ('2023-03-01', '2023-03-31'), ('2023-04-01', '2023-04-30'), ('2023-05-01', '2023-05-31'), ('2023-06-01', '2023-06-30'), ('2023-07-01', '2023-07-31'), ('2023-08-01', '2023-08-31'), ('2023-09-01', '2023-09-30'), ('2023-10-01', '2023-10-31'), ('2023-11-01', '2023-11-30'), ('2023-12-01', '2023-12-31'), ('2024-01-01', '2024-01-31'), ('2024-02-01', '2024-02-29'), ('2024-03-01', '2024-03-31'), ('2024-04-01', '2024-04-30'), ('2024-05-01', '2024-05-31'), ('2024-06-01', '2024-06-30'), ('2024-07-01', '2024-07-31'), ('2024-08-01', '2024-08-31'), ('2024-09-01', '2024-09-30'), ('2024-10-01', '2024-10-31'), ('2024-11-01', '2024-11-30'), ('2024-12-01', '2024-12-31'), ('2025-01-01', '2025-01-31'), ('2025-02-01', '2025-02-28'), ('2025-03-01', '2025-03-31'), ('2025-04-01', '2025-04-30'), ('2025-05-01', '2025-05-31'), ('2025-06-01', '2025-06-30'), ('2025-07-01', '2025-07-31'), ('2025-08-01', '2025-08-31'), ('2025-09-01', '2025-09-30'), ('2025-10-01', '2025-10-31')]

In [27]:
for month_start, month_end in months:
    print(f"Getting data for period: {month_start} to {month_end}")
    data = get_weather_data(month_start, month_end, API_KEY)
    save_data_to_csv(data, 'weather_data_hanoi.csv')

Getting data for period: 2023-01-01 to 2023-01-31

c:\Users\63200744\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.weatherbit.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Error: 429
No valid data to save.
Getting data for period: 2023-02-01 to 2023-02-28

c:\Users\63200744\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.weatherbit.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Error: 429
No valid data to save.
Getting data for period: 2023-03-01 to 2023-03-31

c:\Users\63200744\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.weatherbit.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Error: 429
No valid data to save.
Getting data for period: 2023-04-01 to 2023-04-30

c:\Users\63200744\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.weatherbit.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Error: 429
No valid data to save.
Getting data for period: 2023-05-01 to 2023-05-31

c:\Users\63200744\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.weatherbit.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Error: 429
No valid data to save.
Getting data for period: 2023-06-01 to 2023-06-30

c:\Users\63200744\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.weatherbit.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Error: 429
No valid data to save.
Getting data for period: 2023-07-01 to 2023-07-31

c:\Users\63200744\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.weatherbit.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Error: 429
No valid data to save.
Getting data for period: 2023-08-01 to 2023-08-31

c:\Users\63200744\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.weatherbit.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Error: 429
No valid data to save.
Getting data for period: 2023-09-01 to 2023-09-30

c:\Users\63200744\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.weatherbit.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

KeyboardInterrupt:

# Phần 2: Đọc và Xử lý Dữ liệu cho Dự đoán PM2.5

Trong phần này, chúng ta sẽ:
1. Đọc dữ liệu từ file CSV
2. Khám phá và làm sạch dữ liệu
3. Thực hiện Feature Engineering
4. Chuẩn bị dữ liệu cho model training

## 2.1 Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# For machine learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

## 2.2 Đọc Dữ liệu

In [2]:
# Đọc dữ liệu từ file CSV
df = pd.read_csv('hanoi-aqi-weather-data.csv')

print("=" * 80)
print("THÔNG TIN DỮ LIỆU BAN ĐẦU")
print("=" * 80)
print(f"\nKích thước dữ liệu: {df.shape[0]} dòng x {df.shape[1]} cột")
print(f"\nCác cột trong dataset:")
print(df.columns.tolist())
print("\n" + "=" * 80)

# Hiển thị 5 dòng đầu tiên
df.head()

================================================================================
THÔNG TIN DỮ LIỆU BAN ĐẦU
================================================================================

Kích thước dữ liệu: 8785 dòng x 19 cột

Các cột trong dataset:
['Local Time', 'UTC Time', 'City', 'Country Code', 'Timezone', 'AQI', 'CO', 'NO2', 'O3', 'PM10', 'PM25', 'SO2', 'Clouds', 'Precipitation', 'Pressure', 'Relative Humidity', 'Temperature', 'UV Index', 'Wind Speed']

================================================================================

,Local Time,UTC Time,City,Country Code,Timezone,AQI,CO,NO2,O3,PM10,PM25,SO2,Clouds,Precipitation,Pressure,Relative Humidity,Temperature,UV Index,Wind Speed
0,2023-03-08 00:00:00,2023-03-07T17:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,131,170.6,29.3,53.3,58.8,47.0,67.3,91,0.0,1016,86,21.2,0.0,2.00
1,2023-03-08 01:00:00,2023-03-07T18:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,126,158.7,25.0,54.0,56.3,45.0,65.0,100,0.0,1016,89,21.1,0.0,2.00
2,2023-03-08 02:00:00,2023-03-07T19:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,118,150.2,21.7,55.0,52.5,42.0,65.7,100,0.0,1016,90,20.9,0.0,1.66
3,2023-03-08 03:00:00,2023-03-07T20:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,126,141.6,18.3,56.0,56.3,45.0,66.3,100,0.0,1016,91,20.7,0.0,1.33
4,2023-03-08 04:00:00,2023-03-07T21:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,118,133.1,15.0,57.0,52.5,42.0,67.0,100,0.0,1015,92,20.5,0.0,1.00

In [3]:
# Kiểm tra thông tin chi tiết
print("=" * 80)
print("THÔNG TIN CHI TIẾT VỀ DỮ LIỆU")
print("=" * 80)
df.info()
print("\n" + "=" * 80)
print("THỐNG KÊ MÔ TẢ")
print("=" * 80)
df.describe()

================================================================================
THÔNG TIN CHI TIẾT VỀ DỮ LIỆU
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8785 entries, 0 to 8784
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Local Time         8785 non-null   object
 1   UTC Time           8785 non-null   object
 2   City               8785 non-null   object
 3   Country Code       8785 non-null   object
 4   Timezone           8785 non-null   object
 5   AQI                8785 non-null   int64
 6   CO                 8785 non-null   float64
 7   NO2                8785 non-null   float64
 8   O3                 8785 non-null   float64
 9   PM10               8785 non-null   float64
 10  PM25               8785 non-null   float64
 11  SO2                8785 non-null   float64
 12  Clouds             8785 non-null   int64
 13  Precipitation      8785 non-null   float64
 14  Pressure           8785 non-null   int64
 15  Relative Humidity  8785 non-null   int64
 16  Temperature        8785 non-null   float64
 17  UV Index           8785 non-null   float64
 18  Wind Speed         8785 non-null   float64
dtypes: float64(10), int64(4), object(5)
memory usage: 1.3+ MB

================================================================================
THỐNG KÊ MÔ TẢ
================================================================================

,AQI,CO,NO2,O3,PM10,PM25,SO2,Clouds,Precipitation,Pressure,Relative Humidity,Temperature,UV Index,Wind Speed
count,8785.000000,8785.000000,8785.000000,8785.000000,8785.000000,8785.000000,8785.000000,8785.000000,8785.000000,8785.000000,8785.000000,8785.000000,8785.000000,8785.000000
mean,117.625612,436.146238,27.913887,62.308310,62.310939,49.401244,75.815822,72.992032,0.274132,1010.006602,78.043142,25.281172,1.332863,1.606777
std,53.380563,985.528684,34.063995,45.703768,57.237488,47.699812,45.197389,28.450636,1.029955,7.432832,15.373435,5.649272,1.975192,0.781160
min,21.000000,9.000000,2.000000,0.000000,1.300000,1.000000,0.000000,0.000000,0.000000,994.000000,17.000000,8.600000,0.000000,0.000000
25%,78.000000,124.700000,11.000000,28.100000,31.300000,24.670000,44.000000,58.000000,0.000000,1004.000000,68.000000,21.600000,0.000000,1.000000
50%,104.000000,169.000000,16.700000,52.000000,46.300000,36.000000,70.300000,80.000000,0.000000,1009.000000,82.000000,26.100000,0.600000,1.600000
75%,151.000000,269.200000,28.000000,85.000000,70.000000,55.000000,103.000000,100.000000,0.000000,1016.000000,91.000000,29.200000,2.000000,2.000000
max,500.000000,15956.200000,378.000000,262.000000,604.000000,446.000000,368.000000,100.000000,22.750000,1033.000000,100.000000,40.000000,12.100000,5.200000

In [4]:
# Kiểm tra missing values
print("=" * 80)
print("KIỂM TRA GIÁ TRỊ THIẾU (MISSING VALUES)")
print("=" * 80)
missing_data = pd.DataFrame({
    'Column': df.columns,
    'Missing_Count': df.isnull().sum(),
    'Missing_Percentage': (df.isnull().sum() / len(df) * 100).round(2)
})
missing_data = missing_data[missing_data['Missing_Count'] > 0].sort_values('Missing_Count', ascending=False)

if len(missing_data) > 0:
    print(missing_data.to_string(index=False))
else:
    print("\n✓ Không có giá trị thiếu trong dataset!")
    
print("\n" + "=" * 80)

================================================================================
KIỂM TRA GIÁ TRỊ THIẾU (MISSING VALUES)
================================================================================

✓ Không có giá trị thiếu trong dataset!

================================================================================

## 2.3 Xử lý và Làm sạch Dữ liệu

In [5]:
# Tạo bản sao để xử lý
df_clean = df.copy()

# Chuyển đổi cột thời gian sang datetime
df_clean['Local Time'] = pd.to_datetime(df_clean['Local Time'])
df_clean['UTC Time'] = pd.to_datetime(df_clean['UTC Time'])

# Sắp xếp theo thời gian
df_clean = df_clean.sort_values('Local Time').reset_index(drop=True)

print("=" * 80)
print("XỬ LÝ DỮ LIỆU THÀNH CÔNG")
print("=" * 80)
print(f"\nDữ liệu sau khi xử lý: {df_clean.shape[0]} dòng x {df_clean.shape[1]} cột")
print(f"Khoảng thời gian: {df_clean['Local Time'].min()} đến {df_clean['Local Time'].max()}")
print(f"Tổng số ngày: {(df_clean['Local Time'].max() - df_clean['Local Time'].min()).days} ngày")
print("=" * 80)

df_clean.head()

================================================================================
XỬ LÝ DỮ LIỆU THÀNH CÔNG
================================================================================

Dữ liệu sau khi xử lý: 8785 dòng x 19 cột
Khoảng thời gian: 2023-03-08 00:00:00 đến 2024-03-08 00:00:00
Tổng số ngày: 366 ngày
================================================================================

,Local Time,UTC Time,City,Country Code,Timezone,AQI,CO,NO2,O3,PM10,PM25,SO2,Clouds,Precipitation,Pressure,Relative Humidity,Temperature,UV Index,Wind Speed
0,2023-03-08 00:00:00,2023-03-07 17:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,131,170.6,29.3,53.3,58.8,47.0,67.3,91,0.0,1016,86,21.2,0.0,2.00
1,2023-03-08 01:00:00,2023-03-07 18:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,126,158.7,25.0,54.0,56.3,45.0,65.0,100,0.0,1016,89,21.1,0.0,2.00
2,2023-03-08 02:00:00,2023-03-07 19:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,118,150.2,21.7,55.0,52.5,42.0,65.7,100,0.0,1016,90,20.9,0.0,1.66
3,2023-03-08 03:00:00,2023-03-07 20:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,126,141.6,18.3,56.0,56.3,45.0,66.3,100,0.0,1016,91,20.7,0.0,1.33
4,2023-03-08 04:00:00,2023-03-07 21:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,118,133.1,15.0,57.0,52.5,42.0,67.0,100,0.0,1015,92,20.5,0.0,1.00

## 2.4 Feature Engineering

Tạo các features mới từ dữ liệu hiện có để cải thiện khả năng dự đoán PM2.5

In [6]:
# Tạo bản sao để feature engineering
df_features = df_clean.copy()

print("=" * 80)
print("FEATURE ENGINEERING - TEMPORAL FEATURES")
print("=" * 80)

# 1. Temporal Features (Đặc trưng thời gian)
df_features['year'] = df_features['Local Time'].dt.year
df_features['month'] = df_features['Local Time'].dt.month
df_features['day'] = df_features['Local Time'].dt.day
df_features['hour'] = df_features['Local Time'].dt.hour
df_features['day_of_week'] = df_features['Local Time'].dt.dayofweek  # 0=Monday, 6=Sunday
df_features['day_of_year'] = df_features['Local Time'].dt.dayofyear
df_features['week_of_year'] = df_features['Local Time'].dt.isocalendar().week

# 2. Cyclical Features (cho hour và month)
# Hour
df_features['hour_sin'] = np.sin(2 * np.pi * df_features['hour'] / 24)
df_features['hour_cos'] = np.cos(2 * np.pi * df_features['hour'] / 24)

# Month
df_features['month_sin'] = np.sin(2 * np.pi * df_features['month'] / 12)
df_features['month_cos'] = np.cos(2 * np.pi * df_features['month'] / 12)

# Day of week
df_features['day_of_week_sin'] = np.sin(2 * np.pi * df_features['day_of_week'] / 7)
df_features['day_of_week_cos'] = np.cos(2 * np.pi * df_features['day_of_week'] / 7)

# 3. Phân loại thời gian
def get_season(month):
    if month in [12, 1, 2]:
        return 0  # Winter (Đông)
    elif month in [3, 4, 5]:
        return 1  # Spring (Xuân)
    elif month in [6, 7, 8]:
        return 2  # Summer (Hạ)
    else:
        return 3  # Fall (Thu)

df_features['season'] = df_features['month'].apply(get_season)

# 4. Phân loại giờ trong ngày
def get_time_of_day(hour):
    if 6 <= hour < 12:
        return 0  # Morning
    elif 12 <= hour < 18:
        return 1  # Afternoon
    elif 18 <= hour < 22:
        return 2  # Evening
    else:
        return 3  # Night

df_features['time_of_day'] = df_features['hour'].apply(get_time_of_day)

# 5. Cuối tuần hay không
df_features['is_weekend'] = (df_features['day_of_week'] >= 5).astype(int)

print(f"\n✓ Đã tạo {15} temporal features mới!")
print("\nTemporal features bao gồm:")
temporal_cols = ['year', 'month', 'day', 'hour', 'day_of_week', 'day_of_year', 'week_of_year',
                 'hour_sin', 'hour_cos', 'month_sin', 'month_cos', 'day_of_week_sin', 'day_of_week_cos',
                 'season', 'time_of_day', 'is_weekend']
for i, col in enumerate(temporal_cols, 1):
    print(f"  {i}. {col}")

print("\n" + "=" * 80)

================================================================================
FEATURE ENGINEERING - TEMPORAL FEATURES
================================================================================

✓ Đã tạo 15 temporal features mới!

Temporal features bao gồm:
  1. year
  2. month
  3. day
  4. hour
  5. day_of_week
  6. day_of_year
  7. week_of_year
  8. hour_sin
  9. hour_cos
  10. month_sin
  11. month_cos
  12. day_of_week_sin
  13. day_of_week_cos
  14. season
  15. time_of_day
  16. is_weekend

================================================================================

In [7]:
print("=" * 80)
print("FEATURE ENGINEERING - LAG FEATURES & ROLLING STATISTICS")
print("=" * 80)

# 6. Lag Features (Giá trị quá khứ của PM2.5)
lag_periods = [1, 2, 3, 6, 12, 24]  # 1h, 2h, 3h, 6h, 12h, 24h trước
for lag in lag_periods:
    df_features[f'PM25_lag_{lag}h'] = df_features['PM25'].shift(lag)

print(f"\n✓ Đã tạo {len(lag_periods)} lag features cho PM2.5")
print(f"  Lag periods: {lag_periods} giờ")

# 7. Rolling Statistics (Thống kê trượt)
window_sizes = [3, 6, 12, 24]  # 3h, 6h, 12h, 24h
for window in window_sizes:
    # Rolling mean
    df_features[f'PM25_rolling_mean_{window}h'] = df_features['PM25'].rolling(window=window, min_periods=1).mean()
    # Rolling std
    df_features[f'PM25_rolling_std_{window}h'] = df_features['PM25'].rolling(window=window, min_periods=1).std()
    # Rolling max
    df_features[f'PM25_rolling_max_{window}h'] = df_features['PM25'].rolling(window=window, min_periods=1).max()
    # Rolling min
    df_features[f'PM25_rolling_min_{window}h'] = df_features['PM25'].rolling(window=window, min_periods=1).min()

print(f"\n✓ Đã tạo {len(window_sizes) * 4} rolling statistics features cho PM2.5")
print(f"  Window sizes: {window_sizes} giờ")
print(f"  Metrics: mean, std, max, min")

# 8. Lag features cho các biến khí tượng quan trọng
weather_vars = ['Temperature', 'Relative Humidity', 'Wind Speed', 'Pressure']
for var in weather_vars:
    for lag in [1, 3, 6]:
        df_features[f'{var}_lag_{lag}h'] = df_features[var].shift(lag)

print(f"\n✓ Đã tạo {len(weather_vars) * 3} lag features cho các biến khí tượng")
print(f"  Variables: {', '.join(weather_vars)}")

print("\n" + "=" * 80)

================================================================================
FEATURE ENGINEERING - LAG FEATURES & ROLLING STATISTICS
================================================================================

✓ Đã tạo 6 lag features cho PM2.5
  Lag periods: [1, 2, 3, 6, 12, 24] giờ

✓ Đã tạo 16 rolling statistics features cho PM2.5
  Window sizes: [3, 6, 12, 24] giờ
  Metrics: mean, std, max, min

✓ Đã tạo 12 lag features cho các biến khí tượng
  Variables: Temperature, Relative Humidity, Wind Speed, Pressure

================================================================================

In [8]:
print("=" * 80)
print("FEATURE ENGINEERING - INTERACTION & POLLUTION FEATURES")
print("=" * 80)

# 9. Interaction Features (Tương tác giữa các biến)
# Nhiệt độ và độ ẩm
df_features['temp_humidity_interaction'] = df_features['Temperature'] * df_features['Relative Humidity']

# Gió và độ ẩm
df_features['wind_humidity_interaction'] = df_features['Wind Speed'] * df_features['Relative Humidity']

# Nhiệt độ và gió
df_features['temp_wind_interaction'] = df_features['Temperature'] * df_features['Wind Speed']

# Mây và mưa
df_features['clouds_precip_interaction'] = df_features['Clouds'] * df_features['Precipitation']

print(f"\n✓ Đã tạo 4 interaction features")

# 10. Pollution Ratio Features
# Tỷ lệ PM2.5 trên PM10
df_features['PM25_PM10_ratio'] = df_features['PM25'] / (df_features['PM10'] + 0.001)

# Tỷ lệ các chất ô nhiễm
df_features['CO_NO2_ratio'] = df_features['CO'] / (df_features['NO2'] + 0.001)
df_features['O3_NO2_ratio'] = df_features['O3'] / (df_features['NO2'] + 0.001)

print(f"✓ Đã tạo 3 pollution ratio features")

# 11. Weather Composite Features
# Heat Index (Chỉ số nóng)
df_features['heat_index'] = df_features['Temperature'] * df_features['Relative Humidity'] / 100

# Wind Chill effect
df_features['wind_chill'] = df_features['Temperature'] - (df_features['Wind Speed'] * 0.5)

# Atmospheric stability
df_features['atmospheric_stability'] = df_features['Temperature'] / (df_features['Pressure'] + 0.001)

print(f"✓ Đã tạo 3 weather composite features")

print("\n" + "=" * 80)

================================================================================
FEATURE ENGINEERING - INTERACTION & POLLUTION FEATURES
================================================================================

✓ Đã tạo 4 interaction features
✓ Đã tạo 3 pollution ratio features
✓ Đã tạo 3 weather composite features

================================================================================

In [9]:
print("=" * 80)
print("FEATURE ENGINEERING - POLYNOMIAL & DOMAIN FEATURES")
print("=" * 80)

# 12. Polynomial Features (bậc 2 cho một số biến quan trọng)
important_vars = ['Temperature', 'Relative Humidity', 'Wind Speed', 'Pressure']
for var in important_vars:
    df_features[f'{var}_squared'] = df_features[var] ** 2

print(f"\n✓ Đã tạo {len(important_vars)} polynomial features (bậc 2)")

# 13. Pollution Index (Chỉ số tổng hợp ô nhiễm)
# Tổng các chất ô nhiễm (chuẩn hóa)
pollutants = ['CO', 'NO2', 'O3', 'PM10', 'PM25', 'SO2']
df_features['total_pollutants'] = df_features[pollutants].sum(axis=1)
df_features['avg_pollutants'] = df_features[pollutants].mean(axis=1)

print(f"✓ Đã tạo 2 pollution index features")

# 14. Rate of Change (Tốc độ thay đổi)
df_features['PM25_change_1h'] = df_features['PM25'].diff(1)
df_features['PM25_change_3h'] = df_features['PM25'].diff(3)
df_features['temp_change_1h'] = df_features['Temperature'].diff(1)

print(f"✓ Đã tạo 3 rate of change features")

print("\n" + "=" * 80)

================================================================================
FEATURE ENGINEERING - POLYNOMIAL & DOMAIN FEATURES
================================================================================

✓ Đã tạo 4 polynomial features (bậc 2)
✓ Đã tạo 2 pollution index features
✓ Đã tạo 3 rate of change features

================================================================================

In [10]:
# Tổng kết Features
print("=" * 80)
print("TỔNG KẾT FEATURE ENGINEERING")
print("=" * 80)

original_cols = df_clean.shape[1]
new_cols = df_features.shape[1]
added_features = new_cols - original_cols

print(f"\n📊 Số lượng features:")
print(f"  • Features ban đầu: {original_cols}")
print(f"  • Features mới tạo: {added_features}")
print(f"  • Tổng số features: {new_cols}")

print(f"\n📝 Phân loại features mới:")
print(f"  • Temporal features: 15")
print(f"  • Lag features (PM2.5): 6")
print(f"  • Rolling statistics: 16")
print(f"  • Lag features (weather): 12")
print(f"  • Interaction features: 4")
print(f"  • Pollution ratio features: 3")
print(f"  • Weather composite features: 3")
print(f"  • Polynomial features: 4")
print(f"  • Pollution index: 2")
print(f"  • Rate of change: 3")
print(f"  ────────────────────────")
print(f"  TỔNG CỘNG: {added_features} features mới")

print("\n" + "=" * 80)

# Hiển thị một vài dòng để kiểm tra
print("\nMẫu dữ liệu sau Feature Engineering:")
df_features.head(3)

================================================================================
TỔNG KẾT FEATURE ENGINEERING
================================================================================

📊 Số lượng features:
  • Features ban đầu: 19
  • Features mới tạo: 69
  • Tổng số features: 88

📝 Phân loại features mới:
  • Temporal features: 15
  • Lag features (PM2.5): 6
  • Rolling statistics: 16
  • Lag features (weather): 12
  • Interaction features: 4
  • Pollution ratio features: 3
  • Weather composite features: 3
  • Polynomial features: 4
  • Pollution index: 2
  • Rate of change: 3
  ────────────────────────
  TỔNG CỘNG: 69 features mới

================================================================================

Mẫu dữ liệu sau Feature Engineering:

,Local Time,UTC Time,City,Country Code,Timezone,AQI,CO,NO2,O3,PM10,PM25,SO2,Clouds,Precipitation,Pressure,Relative Humidity,Temperature,UV Index,Wind Speed,year,month,day,hour,day_of_week,day_of_year,week_of_year,hour_sin,hour_cos,month_sin,month_cos,day_of_week_sin,day_of_week_cos,season,time_of_day,is_weekend,PM25_lag_1h,PM25_lag_2h,PM25_lag_3h,PM25_lag_6h,PM25_lag_12h,PM25_lag_24h,PM25_rolling_mean_3h,PM25_rolling_std_3h,PM25_rolling_max_3h,PM25_rolling_min_3h,PM25_rolling_mean_6h,PM25_rolling_std_6h,PM25_rolling_max_6h,PM25_rolling_min_6h,PM25_rolling_mean_12h,PM25_rolling_std_12h,PM25_rolling_max_12h,PM25_rolling_min_12h,PM25_rolling_mean_24h,PM25_rolling_std_24h,PM25_rolling_max_24h,PM25_rolling_min_24h,Temperature_lag_1h,Temperature_lag_3h,Temperature_lag_6h,Relative Humidity_lag_1h,Relative Humidity_lag_3h,Relative Humidity_lag_6h,Wind Speed_lag_1h,Wind Speed_lag_3h,Wind Speed_lag_6h,Pressure_lag_1h,Pressure_lag_3h,Pressure_lag_6h,temp_humidity_interaction,wind_humidity_interaction,temp_wind_interaction,clouds_precip_interaction,PM25_PM10_ratio,CO_NO2_ratio,O3_NO2_ratio,heat_index,wind_chill,atmospheric_stability,Temperature_squared,Relative Humidity_squared,Wind Speed_squared,Pressure_squared,total_pollutants,avg_pollutants,PM25_change_1h,PM25_change_3h,temp_change_1h
0,2023-03-08 00:00:00,2023-03-07 17:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,131,170.6,29.3,53.3,58.8,47.0,67.3,91,0.0,1016,86,21.2,0.0,2.00,2023,3,8,0,2,67,10,0.000000,1.000000,1.0,6.123234e-17,0.974928,-0.222521,1,3,0,NaN,NaN,NaN,NaN,NaN,NaN,47.000000,NaN,47.0,47.0,47.000000,NaN,47.0,47.0,47.000000,NaN,47.0,47.0,47.000000,NaN,47.0,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1823.2,172.0,42.400,0.0,0.799306,5.822327,1.819051,18.232,20.20,0.020866,449.44,7396,4.0000,1032256,426.3,71.050000,NaN,NaN,NaN
1,2023-03-08 01:00:00,2023-03-07 18:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,126,158.7,25.0,54.0,56.3,45.0,65.0,100,0.0,1016,89,21.1,0.0,2.00,2023,3,8,1,2,67,10,0.258819,0.965926,1.0,6.123234e-17,0.974928,-0.222521,1,3,0,47.0,NaN,NaN,NaN,NaN,NaN,46.000000,1.414214,47.0,45.0,46.000000,1.414214,47.0,45.0,46.000000,1.414214,47.0,45.0,46.000000,1.414214,47.0,45.0,21.2,NaN,NaN,86.0,NaN,NaN,2.0,NaN,NaN,1016.0,NaN,NaN,1877.9,178.0,42.200,0.0,0.799275,6.347746,2.159914,18.779,20.10,0.020768,445.21,7921,4.0000,1032256,404.0,67.333333,-2.0,NaN,-0.1
2,2023-03-08 02:00:00,2023-03-07 19:00:00,Hanoi,VN,Asia/Ho_Chi_Minh,118,150.2,21.7,55.0,52.5,42.0,65.7,100,0.0,1016,90,20.9,0.0,1.66,2023,3,8,2,2,67,10,0.500000,0.866025,1.0,6.123234e-17,0.974928,-0.222521,1,3,0,45.0,47.0,NaN,NaN,NaN,NaN,44.666667,2.516611,47.0,42.0,44.666667,2.516611,47.0,42.0,44.666667,2.516611,47.0,42.0,44.666667,2.516611,47.0,42.0,21.1,NaN,NaN,89.0,NaN,NaN,2.0,NaN,NaN,1016.0,NaN,NaN,1881.0,149.4,34.694,0.0,0.799985,6.921340,2.534445,18.810,20.07,0.020571,436.81,8100,2.7556,1032256,387.1,64.516667,-3.0,NaN,-0.2

## 2.5 Chuẩn bị Dữ liệu cho Model Training

In [11]:
print("=" * 80)
print("XỬ LÝ MISSING VALUES VÀ CHUẨN BỊ DỮ LIỆU")
print("=" * 80)

# Kiểm tra missing values sau khi tạo features
print(f"\n1. Số lượng missing values:")
missing_count = df_features.isnull().sum().sum()
print(f"   Tổng missing values: {missing_count:,}")

# Loại bỏ các dòng có missing values (do lag và rolling features)
df_model = df_features.dropna().copy()
print(f"\n2. Sau khi loại bỏ missing values:")
print(f"   • Số dòng trước: {len(df_features):,}")
print(f"   • Số dòng sau: {len(df_model):,}")
print(f"   • Số dòng bị loại: {len(df_features) - len(df_model):,}")

# Xác định các cột không cần thiết cho model
cols_to_drop = ['Local Time', 'UTC Time', 'City', 'Country Code', 'Timezone']

# Xác định target variable
target = 'PM25'

# Xác định features
feature_cols = [col for col in df_model.columns if col not in cols_to_drop + [target]]

print(f"\n3. Cấu trúc dữ liệu cho model:")
print(f"   • Target variable: {target}")
print(f"   • Số lượng features: {len(feature_cols)}")
print(f"   • Số lượng samples: {len(df_model):,}")

# Tạo X và y
X = df_model[feature_cols].copy()
y = df_model[target].copy()

print(f"\n4. Shape của dữ liệu:")
print(f"   • X shape: {X.shape}")
print(f"   • y shape: {y.shape}")

print("\n" + "=" * 80)

================================================================================
XỬ LÝ MISSING VALUES VÀ CHUẨN BỊ DỮ LIỆU
================================================================================

1. Số lượng missing values:
   Tổng missing values: 97

2. Sau khi loại bỏ missing values:
   • Số dòng trước: 8,785
   • Số dòng sau: 8,761
   • Số dòng bị loại: 24

3. Cấu trúc dữ liệu cho model:
   • Target variable: PM25
   • Số lượng features: 82
   • Số lượng samples: 8,761

4. Shape của dữ liệu:
   • X shape: (8761, 82)
   • y shape: (8761,)

================================================================================

In [12]:
print("=" * 80)
print("CHIA DỮ LIỆU TRAIN/TEST")
print("=" * 80)

# Chia dữ liệu theo thời gian (80% train, 20% test)
# Không shuffle để giữ tính tuần tự thời gian
split_index = int(len(X) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]
y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

print(f"\n📊 Phân chia dữ liệu:")
print(f"\n  TRAINING SET:")
print(f"    • X_train shape: {X_train.shape}")
print(f"    • y_train shape: {y_train.shape}")
print(f"    • Tỷ lệ: {X_train.shape[0]/len(X)*100:.1f}%")

print(f"\n  TEST SET:")
print(f"    • X_test shape: {X_test.shape}")
print(f"    • y_test shape: {y_test.shape}")
print(f"    • Tỷ lệ: {X_test.shape[0]/len(X)*100:.1f}%")

print(f"\n📈 Thống kê PM2.5:")
print(f"  Training set - Mean: {y_train.mean():.2f}, Std: {y_train.std():.2f}, Min: {y_train.min():.2f}, Max: {y_train.max():.2f}")
print(f"  Test set     - Mean: {y_test.mean():.2f}, Std: {y_test.std():.2f}, Min: {y_test.min():.2f}, Max: {y_test.max():.2f}")

print("\n" + "=" * 80)

================================================================================
CHIA DỮ LIỆU TRAIN/TEST
================================================================================

📊 Phân chia dữ liệu:

  TRAINING SET:
    • X_train shape: (7008, 82)
    • y_train shape: (7008,)
    • Tỷ lệ: 80.0%

  TEST SET:
    • X_test shape: (1753, 82)
    • y_test shape: (1753,)
    • Tỷ lệ: 20.0%

📈 Thống kê PM2.5:
  Training set - Mean: 47.63, Std: 47.11, Min: 1.00, Max: 446.00
  Test set     - Mean: 56.45, Std: 49.66, Min: 5.00, Max: 417.00

================================================================================

In [13]:
print("=" * 80)
print("DANH SÁCH CHI TIẾT CÁC FEATURES")
print("=" * 80)

# Phân loại features
feature_categories = {
    'Original Features': [col for col in feature_cols if col in df_clean.columns and col not in ['Local Time', 'UTC Time', 'City', 'Country Code', 'Timezone']],
    'Temporal Features': [col for col in feature_cols if any(x in col for x in ['year', 'month', 'day', 'hour', 'week', 'season', 'time_of_day', 'weekend', '_sin', '_cos'])],
    'Lag Features': [col for col in feature_cols if 'lag' in col],
    'Rolling Features': [col for col in feature_cols if 'rolling' in col],
    'Interaction Features': [col for col in feature_cols if 'interaction' in col],
    'Ratio Features': [col for col in feature_cols if 'ratio' in col],
    'Composite Features': [col for col in feature_cols if any(x in col for x in ['heat_index', 'wind_chill', 'atmospheric', 'total_', 'avg_'])],
    'Polynomial Features': [col for col in feature_cols if 'squared' in col],
    'Change Features': [col for col in feature_cols if 'change' in col]
}

for category, cols in feature_categories.items():
    if len(cols) > 0:
        print(f"\n📌 {category} ({len(cols)} features):")
        for i, col in enumerate(cols, 1):
            if i <= 10:  # Hiển thị tối đa 10 features đầu tiên
                print(f"   {i:2d}. {col}")
            elif i == 11:
                print(f"   ... và {len(cols) - 10} features khác")
                break

print("\n" + "=" * 80)
print(f"\n✅ DỮ LIỆU ĐÃ SẴN SÀNG CHO MODEL TRAINING!")
print(f"   • Tổng số features: {len(feature_cols)}")
print(f"   • Training samples: {len(X_train):,}")
print(f"   • Test samples: {len(X_test):,}")
print("\n" + "=" * 80)

================================================================================
DANH SÁCH CHI TIẾT CÁC FEATURES
================================================================================

📌 Original Features (13 features):
    1. AQI
    2. CO
    3. NO2
    4. O3
    5. PM10
    6. SO2
    7. Clouds
    8. Precipitation
    9. Pressure
   10. Relative Humidity
   ... và 3 features khác

📌 Temporal Features (16 features):
    1. year
    2. month
    3. day
    4. hour
    5. day_of_week
    6. day_of_year
    7. week_of_year
    8. hour_sin
    9. hour_cos
   10. month_sin
   ... và 6 features khác

📌 Lag Features (18 features):
    1. PM25_lag_1h
    2. PM25_lag_2h
    3. PM25_lag_3h
    4. PM25_lag_6h
    5. PM25_lag_12h
    6. PM25_lag_24h
    7. Temperature_lag_1h
    8. Temperature_lag_3h
    9. Temperature_lag_6h
   10. Relative Humidity_lag_1h
   ... và 8 features khác

📌 Rolling Features (16 features):
    1. PM25_rolling_mean_3h
    2. PM25_rolling_std_3h
    3. PM25_rolling_max_3h
    4. PM25_rolling_min_3h
    5. PM25_rolling_mean_6h
    6. PM25_rolling_std_6h
    7. PM25_rolling_max_6h
    8. PM25_rolling_min_6h
    9. PM25_rolling_mean_12h
   10. PM25_rolling_std_12h
   ... và 6 features khác

📌 Interaction Features (4 features):
    1. temp_humidity_interaction
    2. wind_humidity_interaction
    3. temp_wind_interaction
    4. clouds_precip_interaction

📌 Ratio Features (3 features):
    1. PM25_PM10_ratio
    2. CO_NO2_ratio
    3. O3_NO2_ratio

📌 Composite Features (5 features):
    1. heat_index
    2. wind_chill
    3. atmospheric_stability
    4. total_pollutants
    5. avg_pollutants

📌 Polynomial Features (4 features):
    1. Temperature_squared
    2. Relative Humidity_squared
    3. Wind Speed_squared
    4. Pressure_squared

📌 Change Features (3 features):
    1. PM25_change_1h
    2. PM25_change_3h
    3. temp_change_1h

================================================================================

✅ DỮ LIỆU ĐÃ SẴN SÀNG CHO MODEL TRAINING!
   • Tổng số features: 82
   • Training samples: 7,008
   • Test samples: 1,753

================================================================================

## 2.6 Lưu Dữ liệu đã Xử lý

In [14]:
# Lưu dữ liệu đã được feature engineering
df_model.to_csv('hanoi_pm25_features.csv', index=False)
print("✓ Đã lưu dữ liệu với features vào: hanoi_pm25_features.csv")

# Lưu danh sách features
import json
feature_info = {
    'target': target,
    'features': feature_cols,
    'n_features': len(feature_cols),
    'n_samples': len(df_model),
    'feature_categories': {k: v for k, v in feature_categories.items()}
}

with open('feature_info.json', 'w', encoding='utf-8') as f:
    json.dump(feature_info, f, indent=2, ensure_ascii=False)
print("✓ Đã lưu thông tin features vào: feature_info.json")

# Lưu train/test sets
X_train.to_csv('X_train.csv', index=False)
X_test.to_csv('X_test.csv', index=False)
y_train.to_csv('y_train.csv', index=False)
y_test.to_csv('y_test.csv', index=False)
print("✓ Đã lưu train/test sets vào các file CSV")

print("\n" + "=" * 80)
print("HOÀN THÀNH FEATURE ENGINEERING!")
print("=" * 80)

✓ Đã lưu dữ liệu với features vào: hanoi_pm25_features.csv
✓ Đã lưu thông tin features vào: feature_info.json
✓ Đã lưu train/test sets vào các file CSV

================================================================================
HOÀN THÀNH FEATURE ENGINEERING!
================================================================================
✓ Đã lưu train/test sets vào các file CSV

================================================================================
HOÀN THÀNH FEATURE ENGINEERING!
================================================================================